var words = [
  ['be', 'was/were'],
  ['beat', 'beat'],
  ['buy', 'bought'],
  ['catch', 'caught'],
  ['come', 'came'],
  ['do', 'did'],
  ['eat', 'ate'],
  ['find', 'found'],
  ['get', 'got'],
  ['get up', 'got up'],
  ['go', 'went'],
  ['have', 'had'],
  ['hear', 'heard'],
  ['know', 'knew'],
  ['leave', 'left'],
  ['make', 'made'],
  ['meet', 'met'],
  ['read', 'read'],
  ['ride', 'rode'],
  ['say', 'said'],
  ['see', 'saw'],
  ['sit', 'sat'],
  ['speak', 'spoke'],
  ['spend', 'spent'],
  ['swim', 'swam'],
  ['take', 'took'],
  ['tell', 'told'],
  ['think', 'thought'],
  ['wear', 'wore'],
  ['win', 'won'],
  ['write', 'wrote'],
];
